### ISSUE TITLE
{baseURL} isn't being applied in .css files.

### ISSUE THREAD

**Issue by jeffschwartz** [4awpawz/fusion.ssg#99]
```css
.hero {
    background-image: url("{baseURL}/media/cat-background-img.jpg");
    background-color: transparent;
    color: var(--forground-color);
    padding: .5rem;
}
```
